### ISSUE TITLE
[Sprinting] No stamina cost when in air

### ISSUE THREAD

**Issue by Satton2** [TTT-2/TTT2#1017]
When sprinting, you can constantly jump to "stop" the reduction of stamina while keeping the speed.

As I understand, stamina drain in only applied when you are on the ground, which is not how it should work in my opinion, since you can abuse the system and sprint for about 60% longer than you suppose to.

My suggestion here is to always drain stamina when sprinting, regardless of being on ground or in air.

**Comment by Satton2** [comment]
Also, no stamina cost when in water.

**Comment by 400Ferrets** [comment]
I think while not perfect, it makes the most sense to disable stamina drain in the air, because the player could simply release the sprint key while airborne and achieve the same effect.  

you might then recommend lowering stamina based on speed, but how would you keep map objects like cannons from removing all of a player's stamina when they launch them?  

if you instead chose to add a delay to stamina loss when the button is released, it would make the system feel sluggish and unresponsive. (players would not appreciate this, especially in an engine like source where people are used to instant response to their inputs)

It is a much more difficult problem than it seems on the surface, and every solution has tradeoffs.

**Comment by Satton2** [comment]
> I think while not perfect, it makes the most sense to disable stamina drain in the air, because the player could simply release the sprint key while airborne and achieve the same effect.
> 
> you might then recommend lowering stamina based on speed, but how would you keep map objects like cannons from removing all of a player's stamina when they launch them?
> 
> if you instead chose to add a delay to stamina loss when the button is released, it would make the system feel sluggish and unresponsive. (players would not appreciate this, especially in an engine like source where people are used to instant response to their inputs)
> 
> It is a much more difficult problem than it seems on the surface, and every solution has tradeoffs.

First, hello!
Second, nah... I don't think that this issue should be discussed much, so I will try to be short.

You see, I look at this from the perspective of logic and balance.
1) If we take the perspective of logic, you should lose stamina when jumping and fast (_while sprinting_) swimming (both action require some "power" to be made).
2) If we take the perspective of balance, people actually have (with some limitations) an ability to airstrafe and bunnyhop, and let's not forget about many speed related passive/active bonuses that you can get from various default and custom equipment.

The only thing I want is to make it work right, and by saying that I want stamina to be drained whenever the sprinting feature (function) is active. You may not like my way of looking at that issue, but it's an issue, and I believe that I suggested a simple and balanced way of dealing with that.

**Comment by wgetJane** [comment]
> 1. If we take the perspective of logic, you should lose stamina when jumping and fast (_while sprinting_) swimming (both action require some "power" to be made).

the solution i use is making players lose stamina based on their horizontal speed, since jumping carries over your horizontal speed and there's zero air friction
the amount of stamina lost is about the same as if you just sprinted the same distance on the ground (which is actually quite a lot at the default settings, over half of the stamina bar should be lost per jump)

btw here's what it looks like to sprint normally vs sprint-jumping:

https://user-images.githubusercontent.com/52103358/233748950-16813127-2bf8-44b8-9225-246e2b97add5.mp4

**Comment by Histalek** [comment]
> stamina drain in only applied when you are on the ground

> there is no stamina cost when in water (swimming)

these two should be directly related. If i remember correctly this was changed on purpose sometime ago, i would need to check why it was done.

Regarding the fix for this issue i'd propose the following approach:
1. Look at why this behaviour was changed to only drain stamina while on ground and possibly reverse that.
2. If 1. is not feasible or has other drawbacks: introduce a stamina penalty if a player jumps while sprinting (lose a specific amount of stamina instantly)
Making the amount of stamina lost a convar would also mean being able to get the current behaviour by setting that convar to 0.

**Comment by Histalek** [comment]
324c6d7 is probably the culprit as it introduced the only `OnGround()` check in our codebase. Simply reverting that change won't fix the issue though

**Comment by Histalek** [comment]
This should be fixed by #1035 
Please reopen if that's not the case.
