### ISSUE TITLE
TTT2 Compatible Weapon Mods Not Available In 'Edit Equipment' Tab

### ISSUE THREAD

**Issue by SolarSupremacy** [TTT-2/TTT2#1019]
I have various guns installed from this collection on my server: https://steamcommunity.com/workshop/filedetails/?id=253746161

Only the Traitor's Dragon Elites for whatever reason are actually available in game.

**Comment by Satton2** [comment]
Tested only the first 7 of them on the last TTT2 version.
Looks like the problem on your side, since I have all seven in the related tabs. I suggest you to check for any broken or conflicting addons or make sure that you are using the last TTT2 version.

![image](https://user-images.githubusercontent.com/23385240/216825056-c31e457a-e668-4dd1-b017-6899ef77e09e.png)
![image](https://user-images.githubusercontent.com/23385240/216825092-736e0095-86da-4de8-8c21-685c9c230de4.png)

**Comment by SolarSupremacy** [comment]
I hate always finding the solution immediately after asking for help, especially when I spent three days trying to fix it before asking.

I fixed it by wiping the `steam_cache/appworkshop_4000.acf` installed block.

**Comment by TimGoll** [comment]
Great that you solved it!
