### ISSUE TITLE
[UI] Combobox sensitive to value type

### ISSUE THREAD

**Issue by ZenBre4ker** [TTT-2/TTT2#1071]
As the Combox doesnt work if it is used with other values than strings, there should be a check.

This doesnt work:
![grafik](https://github.com/TTT-2/TTT2/assets/72046466/fe84e968-b8dd-4add-9cf1-0cca0a1df381)

This does:
![grafik](https://github.com/TTT-2/TTT2/assets/72046466/b5c6b614-20f3-4b8f-9c79-fb6046f4f3f2)

Note to self:
Check why value has to be given as string.
Use a tostring( ) to make sure its a string.

**Comment by EntranceJew** [comment]
I feel bad that you had to retrace this, because I discovered I had found this out at some point prior -- but I wound up not even utilizing the combobox and in the end and I thought I was using it incorrectly to begin with. 

I *believe* the issue has more to do with the OnSelect* callback, more-over any of the internals themselves.

**Comment by AaronMcKenney** [comment]
For better or worse, most of my roles make use of integer enums, so this one is pretty important to me.

**Comment by NickCloudAT** [comment]
@ZenBre4ker have you already looked at this? I just did and found a "tostring" for "choice.value" in the following line will fix it:
https://github.com/TTT-2/TTT2/blob/master/gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua#L322C7-L322C7

If you want I can open a PR for this.

**Comment by ZenBre4ker** [comment]
Sounds good 👍

**Comment by NickCloudAT** [comment]
This can be closed now
