### ISSUE TITLE
[Feature] Rework Radio

### ISSUE THREAD

**Issue by TimGoll** [TTT-2/TTT2#1095]
- Remove the radio UI from the shop
- add a custom menu with a custom keybind
- the keybind should be listed in the equipment section if a player owns a radio

@EntranceJew had a few feature ideas that could be added here as well

**Comment by EntranceJew** [comment]
Yes, the major thing being:

- items become able to register their main functionality sound effects, so that other weapons (such as the radio) can intentionally invoke a noise that is the same as it
- concommand ttt_radio plays using the format `ttt_radio c4beep [n]` instead of using the arbitrary entity ID (a netmessage workaround hack atm), where `[n]` is a radio in the player or team's control, but defaults to their first owned one

**Comment by TimGoll** [comment]
RE point two: Should we add a keybind for this? Something like "play last sound"? Then we can remove the command that is annoying

**Comment by EntranceJew** [comment]
repeat last sound bind would be a worthwhile, but the ability to quickly tell a "story" with radio commands IMO such as "footsteps => death scream" is still the priority.
on a custom menu, if it were a radial then "repeat last command" would probably be the center option.
![image](https://github.com/TTT-2/TTT2/assets/5711436/943a8640-751b-4a3e-befc-9bcd04142395)
horrible diagram warranted

there should still be the annoying concommand, to call the sounds individually, just change the structure of it, since it's being abused, and people with other radial bind menus might like to manually remap them the way I do with the radio callouts

**Comment by TimGoll** [comment]
This was done in #1437 

We might add a radial menu in the future, but the main task of this issue is done
