### ISSUE TITLE
confirmed corpses don't show role icon in target ID

### ISSUE THREAD

**Issue by EntranceJew** [TTT-2/TTT2#1205]
## Your version of TTT2 (mandatory)

Leave one of the following:

- Latest GitHub version

## Describe the bug (mandatory)

Confirmed bodies aren't showing the role icon in targetID

![image](https://github.com/TTT-2/TTT2/assets/5711436/d255cafd-2eea-40d5-9341-ffb5727ebe8e)

## To reproduce

Steps to reproduce the behaviour:

1. Kill somebody.
2. Confirm their body.
3. Look at their corpse.
4. Toe tag.

## Expected behaviour

Seeing their role and name in team color.

## Context (please provide as much as you can)

- Previously, there would be a bug where sometimes corpses would **sometimes** remain showing the toe tag icon, even after the role was known.
- Consistently showing the toetag is a lot better than occasionally having a corpse that keeps it.

**Comment by TimGoll** [comment]
Slightly related: The bodysearch window added the info about credits in the corpse to everybody. We should probably bring this change to targetID as well?

**Comment by Spanospy** [comment]
> Slightly related: The bodysearch window added the info about credits in the corpse to everybody. We should probably bring this change to targetID as well?

Personally, I think it would make credit checking way too easy for innocents. Anyone could just keep an eye on a body and immediately know when credits were taken from it (rather than needing to check the body first to make sure).

**Comment by Racpy** [comment]
> > Slightly related: The bodysearch window added the info about credits in the corpse to everybody. We should probably bring this change to targetID as well?
> 
> Personally, I think it would make credit checking way too easy for innocents. Anyone could just keep an eye on a body and immediately know when credits were taken from it (rather than needing to check the body first to make sure).

My thoughts and opinions:
I think it's normal for everyone to know that there are credits on corpse.

Play status in recent days: If there are credits on corpse but not reported, the role who can open shop will try to let other players search corpse to reduce suspicion.
If search player not take credits, It will secretly take it away when others no longer focus on the corpse have credits.

This is what detectives and the innocents need to do, protect these corpse to prevent other teams from stealing these credits to increase their win rate.
maybe it would make more sense to search body first and then know the corpse has credits on it.
because the role who can open shop can immediately know that the corpse has credits without search body first.

You may not always find credits on corpse, as the killer will try his best to kill in a less crowded area, search and take the credits directly, or spend them all at the beginning of the round.

There may also be more unexpected situations and the acting skills of the players.
