### ISSUE TITLE
SERIALKILLER non-working shop

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#412]
As you can see in the screenshot, the top says that "you already have an order, wait for it to be received" Although the person only received the role.
https://steamuserimages-a.akamaihd.net/ugc/790876186813472218/DAC3BF59F3D86C21EB7E7330E28EDCC538775165/

**Comment by saibotk** [comment]
So after some research, i found out, that this happens, because of the old version of the jester in the Workshop. For now, you could use the Github version [here](https://github.com/TTT-2/ttt2-role_jes). That should fix the problem, additionally i will add some code to the TTT2 base, to prevent that such errors will affect new rounds.

Also i added a new task to our todo list, to refactor the equipment/weapon give system.
