### ISSUE TITLE
Some bugs with the door and other

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/TTT2#537]
Version 
Last github version

1. Even if I change the hp value of the doors, it updates only after they are damaged (Present in the video)
2. With the new ttt2-wep_doorlocker i find that sometimes the new thermal module do not starts
(Present in the video)
3. With the new ttt2-wep_doorlocker when you have the doorlocker equipped (and the thermal module starts) and you drop it, you get stuck with the "thermal vision" on
(Present in the video)

Video 
https://youtu.be/TB4MJzw3puE

**Comment by TimGoll** [comment]
1. Ah, I see, the variable is not initialized properly, thanks!
2. Yes, I know. This is because the doors modules is not initialized on map connect. I'm already aware of this, but I'm not quite sure how to fix it. It should work after a mapchange though.
3. Yes, I totally forgot to handle the weapon drop. Thanks!

**Comment by TimGoll** [comment]
1 and 3 are fixed

**Comment by TimGoll** [comment]
Everything should work now as intended
