### ISSUE TITLE
Strange confirmation of death

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#557]
![213](https://user-images.githubusercontent.com/7480655/83540076-7fbe9180-a500-11ea-9840-e0aad026ef0d.png)
![2323](https://user-images.githubusercontent.com/7480655/83540080-81885500-a500-11ea-8fb5-90b51619b095.png)
As you can see in the first screenshot, in line 2, dok441's body is confirmed, but in the second screenshot, you can see that my body has not been examined, so this is a false death confirmation message.

**Comment by TimGoll** [comment]
Are you sure this is a TTT2 bug? Because I did never notice this problem.

**Comment by dok441** [comment]
I here is show as it there is, system confirming death applies to TTT2 how I understand.

**Comment by TimGoll** [comment]
What I tried to say was: maybe some other addon interferes with it?

Does it always happen? Or just sometimes? How to reproduce?

**Comment by TimGoll** [comment]
I looked into it and it isn't a bug, it is a feature. Actually a feature from vanilla TTT. It is called killlist. See: 
![image](https://user-images.githubusercontent.com/13639408/83541064-6e25bb80-a4f9-11ea-8ee2-daff61c43370.png)

This means, you're indirectly confirmed. Which you're confirmed that you're dead because your killer was confirmed. This is indicated with the grey square with a cross on it in the miniscoreboard.

If you don't like this behaviour set `ttt2_confirm_killlist` to `0`

**Comment by dok441** [comment]
This rarely happens. Addons that are associated with confirmation of death are not present.

**Comment by dok441** [comment]
Understood, thank you.
