### ISSUE TITLE
Preservation of last traitors.

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#595]
2 pictures show a bug, the first picture shows how you point at a person and he writes that he is a traitor, although he was a couple of rounds ago. The 2 screenshot shows that a person retains past traitors in the table, although the traitor is completely different. At some point, a person lost it. All this happens in a person at the same time and disappears too.
https://media.discordapp.net/attachments/336821665352908810/726107637728411688/2020-06-26_21-09-50.png?width=891&height=501
https://media.discordapp.net/attachments/336821665352908810/726107682335096883/2020-06-26_21-10-36.png?width=891&height=501

**Comment by TimGoll** [comment]
I'm not 100% sure this is caused by TTT2. I'm not saying that it definitely isn't, but this could be caused by any addon that modifies the local information about players.

**Comment by saibotk** [comment]
@dok441 Please use our Issue template for reporting bugs next time. Usually we would close such reports, as they are too complex to resolve without additional context and we added a notice, that issues/bugreports must follow the template or will be closed otherwise. 

It just saves us much more time, if we dont need to ask about the context again and again. 
I hope that this is understandable.

**Comment by ThePlatinumGhost** [comment]
@dok441 I have a question about the first bug
the player was a jester?
i have same issue but is caused by the jester
If it wasn't Jester then forget what I said
